% Начало программы %
begin
    var
        % Объявление переменных %
        var a, b, c, d, f: #;
            e: @;;


    a assign 5o plus 10 mult 12h minus 0101b;

    for c assign 1 val 10 do enter c;

    while c LT 20 do c assign c plus 10o next;

    displ a plus 4, c;

    enter d;

    if d EQ 13 then b assign 10h
    else begin 
        b assign 10o : e assign 12.34
        f assign 4
    end

end
